# =======================================================
# Cloudflare WARP Global Adaptor - Universal Language Pack
# Version: 1.1 (Externalized for warp.sh v1.0)
# =======================================================

# 1. English (Default)
L_1_menu_title="Cloudflare WARP Global Adaptor v1.0"
L_1_hw_info="Hardware Profile: %s | RAM: %sMB"
L_1_opt_1="1. Intelligent Deployment (Zero Trust / Free)"
L_1_opt_2="2. Deep Uninstall & Cleanup"
L_1_opt_0="0. Exit"
L_1_back_hint="Hint: Enter '0' at any prompt to return to main menu."
L_1_ctrl0_hint="Force Stop: Press Ctrl+C."
L_1_lang_select="Select Language / 请选择语言:"
L_1_installing="--- 5. Core Functions --- Installing Cloudflare WARP..."
L_1_verifying="Verifying registration status..."
L_1_mtu_detect="Detecting optimal Path MTU..."
L_1_done="Operation completed successfully."
L_1_fail="Operation failed. Please check network/token."
L_1_team_ask="Use Zero Trust Team account? (y/n):"
L_1_token_ask="Enter Team Token (Optional for manual):"
L_1_name_ask="Enter Team Name (Org):"
L_1_mode_ask="Select Mode: 1. Global (WARP) 2. Proxy (SOCKS5):"

# 2. 中文 (Chinese Simplified)
L_2_menu_title="Cloudflare WARP 全环境智能适配版 v1.0"
L_2_hw_info="硬件配置档: %s | 物理内存: %sMB"
L_2_opt_1="1. 智能一键部署 (零信任 Teams / 免费版)"
L_2_opt_2="2. 深度卸载与环境清理"
L_2_opt_0="0. 退出脚本"
L_2_back_hint="提示：在任何输入框输入 0 即可返回主菜单。"
L_2_ctrl0_hint="强制终止：直接按 Ctrl+C。"
L_2_lang_select="请选择脚本语言:"
L_2_installing="--- 5. 核心功能 --- 正在安装 Cloudflare WARP..."
L_2_verifying="正在验证账户注册状态..."
L_2_mtu_detect="正在探测当前网络最优 MTU..."
L_2_done="操作成功完成。"
L_2_fail="操作失败，请检查网络环境或 Token 有效性。"
L_2_team_ask="是否使用 Zero Trust Team 团队账户? (y/n):"
L_2_token_ask="输入 Team Token (若无则留空进行浏览器认证):"
L_2_name_ask="输入 Team Name (组织名称):"
L_2_mode_ask="选择模式: 1. 全局虚拟网卡模式 2. SOCKS5 代理模式:"

# 3. Русский (Russian)
L_3_menu_title="Cloudflare WARP Интеллектуальный адаптер v1.0"
L_3_hw_info="Профиль: %s | ОЗУ: %sМБ"
L_3_opt_1="1. Интеллектуальное развертывание (Teams / Бесплатно)"
L_3_opt_2="2. Полное удаление и очистка"
L_3_opt_0="0. Выход"
L_3_back_hint="Подсказка: введите '0' для возврата в меню."
L_3_ctrl0_hint="Остановка: Ctrl+C."
L_3_installing="--- 5. Основные функции --- Установка Cloudflare WARP..."
L_3_verifying="Проверка регистрации..."
L_3_mtu_detect="Определение оптимального MTU..."
L_3_done="Операция успешно завершена."
L_3_fail="Ошибка. Проверьте сеть или токен."
L_3_team_ask="Использовать Zero Trust Team? (y/n):"
L_3_token_ask="Введите Team Token (необязательно):"
L_3_name_ask="Введите имя команды (Org):"
L_3_mode_ask="Режим: 1. Глобальный (WARP) 2. Прокси (SOCKS5):"

# 4. فارسی (Persian)
L_4_menu_title="نصب‌کننده هوشمند Cloudflare WARP v1.0"
L_4_hw_info="سخت‌افزار: %s | حافظه: %sMB"
L_4_opt_1="1. استقرار هوشمند (تیم‌ها / رایگان)"
L_4_opt_2="2. حذف کامل و پاکسازی محیط"
L_4_opt_0="0. خروج"
L_4_back_hint="راهنما: برای بازگشت به منوی اصلی '0' را وارد کنید."
L_4_ctrl0_hint="توقف اجباری: Ctrl+C."
L_4_installing="--- 5. توابع اصلی --- در حال نصب Cloudflare WARP..."
L_4_verifying="در حال بررسی وضعیت ثبت‌نام..."
L_4_mtu_detect="در حال شناسایی بهترین MTU..."
L_4_done="عملیات با موفقیت انجام شد."
L_4_fail="عملیات ناموفق بود. شبکه یا توکن را بررسی کنید."
L_4_team_ask="آیا از حساب Team استفاده می‌کنید؟ (y/n):"
L_4_token_ask="توکن تیم را وارد کنید (اختیاری):"
L_4_name_ask="نام تیم را وارد کنید:"
L_4_mode_ask="انتخاب حالت: 1. جهانی (WARP) 2. پروکسی (SOCKS5):"

# 5. 日本語 (Japanese)
L_5_menu_title="Cloudflare WARP 全環境適応版 v1.0"
L_5_hw_info="プロファイル: %s | メモリ: %sMB"
L_5_opt_1="1. インテリジェント展開 (Teams / 無料版)"
L_5_opt_2="2. ディープアンインストールとクリーンアップ"
L_5_opt_0="0. 終了"
L_5_back_hint="ヒント：'0' を入力するとメインメニューに戻ります。"
L_5_ctrl0_hint="強制終了: Ctrl+C。"
L_5_installing="--- 5. 主要機能 --- Cloudflare WARP をインストール中..."
L_5_verifying="登録状態を確認中..."
L_5_mtu_detect="最適な MTU を検出中..."
L_5_done="正常に完了しました。"
L_5_fail="失敗しました。ネットワークまたはトークンを確認してください。"
L_5_team_ask="Zero Trust Team アカウントを使用しますか？ (y/n):"
L_5_token_ask="チームトークンを入力 (任意):"
L_5_name_ask="チーム名を入力してください:"
L_5_mode_ask="モード選択: 1. グローバル (WARP) 2. プロキシ (SOCKS5):"

# 6. Español (Spanish)
L_6_menu_title="Adaptador Global Cloudflare WARP v1.0"
L_6_hw_info="Perfil: %s | RAM: %sMB"
L_6_opt_1="1. Despliegue Inteligente (Teams / Gratis)"
L_6_opt_2="2. Desinstalación Profunda y Limpieza"
L_6_opt_0="0. Salir"
L_6_back_hint="Pista: Ingrese '0' para volver al menú principal."
L_6_ctrl0_hint="Parada forzada: Ctrl+C."
L_6_installing="--- 5. Funciones principales --- Instalando WARP..."
L_6_verifying="Verificando registro..."
L_6_mtu_detect="Detectando MTU óptimo..."
L_6_done="Operación completada con éxito."
L_6_fail="Fallo. Verifique la red o el token."
L_6_team_ask="¿Usar cuenta de Team? (y/n):"
L_6_token_ask="Ingrese el Token del equipo (Opcional):"
L_6_name_ask="Nombre del equipo:"
L_6_mode_ask="Modo: 1. Global (WARP) 2. Proxy (SOCKS5):"

# 7. Français (French)
L_7_menu_title="Adaptateur Global Cloudflare WARP v1.0"
L_7_hw_info="Profil : %s | RAM : %sMo"
L_7_opt_1="1. Déploiement Intelligent (Teams / Gratuit)"
L_7_opt_2="2. Désinstallation Complète"
L_7_opt_0="0. Quitter"
L_7_back_hint="Conseil : Entrez '0' pour revenir au menu principal."
L_7_ctrl0_hint="Arrêt forcé : Ctrl+C."
L_7_installing="--- 5. Fonctions de base --- Installation de WARP..."
L_7_verifying="Vérification de l'enregistrement..."
L_7_mtu_detect="Détection du MTU optimal..."
L_7_done="Opération terminée avec succès."
L_7_fail="Échec. Vérifiez le réseau ou le jeton."
L_7_team_ask="Utiliser un compte Team ? (y/n) :"
L_7_token_ask="Entrez le jeton (Optionnel) :"
L_7_name_ask="Nom de l'équipe :"
L_7_mode_ask="Mode : 1. Global (WARP) 2. Proxy (SOCKS5) :"

# 8. Deutsch (German)
L_8_menu_title="Cloudflare WARP Globaler Adapter v1.0"
L_8_hw_info="Hardware: %s | RAM: %sMB"
L_8_opt_1="1. Intelligente Bereitstellung (Teams / Kostenlos)"
L_8_opt_2="2. Tiefen-Deinstallation"
L_8_opt_0="0. Beenden"
L_8_back_hint="Hinweis: Geben Sie '0' ein, um zum Menü zurückzukehren."
L_8_ctrl0_hint="Stopp: Ctrl+C."
L_8_installing="--- 5. Kernfunktionen --- WARP wird installiert..."
L_8_verifying="Registrierungsstatus wird geprüft..."
L_8_mtu_detect="Optimaler MTU wird gesucht..."
L_8_done="Erfolgreich abgeschlossen."
L_8_fail="Fehlgeschlagen. Netzwerk oder Token prüfen."
L_8_team_ask="Team-Konto verwenden? (y/n):"
L_8_token_ask="Team-Token eingeben (Optional):"
L_8_name_ask="Team-Name eingeben:"
L_8_mode_ask="Modus: 1. Global (WARP) 2. Proxy (SOCKS5):"

# 9. 한국어 (Korean)
L_9_menu_title="Cloudflare WARP 글로벌 어댑터 v1.0"
L_9_hw_info="하드웨어: %s | RAM: %sMB"
L_9_opt_1="1. 지능형 배포 (Teams / 무료)"
L_9_opt_2="2. 전체 삭제 및 환경 정리"
L_9_opt_0 Korean_opt_0="0. 종료"
L_9_back_hint="힌트: '0'을 입력하면 주 메뉴로 돌아갑니다."
L_9_ctrl0_hint="강제 중지: Ctrl+C."
L_9_installing="--- 5. 핵심 기능 --- WARP 설치 중..."
L_9_verifying="등록 상태 확인 중..."
L_9_mtu_detect="최적 MTU 탐색 중..."
L_9_done="성공적으로 완료되었습니다."
L_9_fail="실패했습니다. 네트워크 또는 토큰을 확인하십시오."
L_9_team_ask="Team 계정을 사용하시겠습니까? (y/n):"
L_9_token_ask="팀 토큰 입력 (선택 사항):"
L_9_name_ask="팀 이름 입력:"
L_9_mode_ask="모드 선택: 1. 전체 (WARP) 2. 프록시 (SOCKS5):"

# 10. Português (Portuguese)
L_10_menu_title="Adaptador Global Cloudflare WARP v1.0"
L_10_hw_info="Perfil: %s | RAM: %sMB"
L_10_opt_1="1. Implantação Inteligente (Teams / Grátis)"
L_10_opt_2="2. Desinstalação Profunda"
L_10_opt_0="0. Sair"
L_10_back_hint="Dica: Digite '0' para voltar ao menu principal."
L_10_ctrl0_hint="Parada forçada: Ctrl+C."
L_10_installing="--- 5. Funções principais --- Instalando o WARP..."
L_10_verifying="Verificando o registro..."
L_10_mtu_detect="Detectando o melhor MTU..."
L_10_done="Operação concluída com sucesso."
L_10_fail="Falha. Verifique a rede ou o token."
L_10_team_ask="Usar conta Team? (y/n):"
L_10_token_ask="Digite o Token da equipe (Opcional):"
L_10_name_ask="Nome da equipe:"
L_10_mode_ask="Modo: 1. Global (WARP) 2. Proxy (SOCKS5):"
